[tool.poetry]
name = "api"
version = "0.0.1"
description = ""
authors = ["ArielMAJ <ariel.maj@hotmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
fastapi = "^0.105.0"
uvicorn = "^0.24.0.post1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
